### ISSUE TITLE
directly share a google drive link?

### ISSUE THREAD

**Issue by vainaixr** [yaoyao-liu/mini-imagenet-tools#2]
is it possible to share a google drive link for mini imagenet, that I store in my google drive, so access it directly in google colab?

**Comment by yaoyao-liu** [comment]
Thanks for your interest in my work.
If you want to directly download the processed images for miniImageNet, you may visit the following link: [https://meta-transfer-learning.yaoyao-liu.com/download/](https://meta-transfer-learning.yaoyao-liu.com/download/)
As the miniImageNet dataset is sampled from the ImageNet, you need agree to the terms of ImageNet, and use these processed images only for non-commercial research and educational purposes.

**Comment by vainaixr** [comment]
ok, thanks.

just one more question, is it possible to store it in untarred format, and is there any issue in storing it in untarred format, because most of the programs require it in untarred format.

**Comment by yaoyao-liu** [comment]
I uploaded the tar file because it would be more convenient to download and verify `md5sum` for the dataset. The speed would be very slow when uploading and downloading many small files. 

You could download the tar file, untar it and re-upload by yourself. You may create a pull request to share your re-upload files' link in the repo. Thanks a lot for your contributions.

**Comment by yaoyao-liu** [comment]
Thanks for the contributions by @vainaijr. As the google drive sharing link has been added to the `README.md`, I'm going the close this issue. Feel free to create another issue if you have any other questions.
